import type { Metadata } from "next";
import { Poly, Poppins } from "next/font/google";
import "./globals.css";

// This applies the Poly font and creates a CSS variable --font-poly
const poppins = Poppins({
  weight: '400',           // Set weight to regular
  style: 'normal',         // Set style to normal
  subsets: ['latin'],      // Latin subset
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className={poppins.className} >
        {children}
      </body>
    </html>
  );
}
